name: Pitch
description: 'Do you want me to work on something? Time to pitch!'
title: ''
labels: ['Pitch']
body:
  - type: input
    id: link-to-issue
    attributes:
      label: 'Link to issue/PR'
      description: "Please provide a link to the issue or pull request that you want me to consider for the next cycle. If it doesn't have an issue, you should probably start by creating one. Remember we should work in community!"
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: 'Anything else?'
      description: 'Is there anything else you want me to know? If so, please write it down here.'


